### ISSUE TITLE
User API to get KSP number of iterations after convergence

### ISSUE THREAD

**Issue by ericneiva** [gridap/GridapPETSc.jl#30]
In `GridapPETSc v0.3.0` the API no longer allows to extract the number of iterations at which `ksp` converged.

Old API:
```
function PETSc_get_number_of_iterations(ps::PETScSolver)
    KSPGetIterationNumber!(ps.ksp)
end
```

The `ksp` is no longer an attribute of `PETScSolver`, but `PETScSolverNS`. How can the user extract the number of iterations now?

**Comment by fverdugo** [comment]
Indeed, now `PetscSolver` does not handle any state change (as Gridap `LinearSolver` types are conceived). The state is handled by the numerical setup object, `PetscSolverNS`, (NS is for "numerical setup"). 

```julia
solver = PetscSolver()
ss = symbolic_setup(solver,A)
ns = numerica_setup(ss,A)
solve!(x,ns,b)
niters = Ref{PetscInt}()
@check_error_code KSPGetIterationNumer(ns.ksp[],niters)
println("num iters = $(niters[])")
```

**Comment by ericneiva** [comment]
Okay, many thanks @fverdugo. I leave here a complete snippet for future reference.

```julia
solver = PETScSolver()
ss = symbolic_setup(solver,A)
ns = numerical_setup(ss,A)
x = similar(b)
solve!(x,ns,b)
niters = Ref{PetscInt}()
@check_error_code GridapPETSc.PETSC.KSPGetIterationNumber(ns.ksp[],niters)
println("num iters = $(niters[])")
```
