### ISSUE TITLE
Store MPI.Comm in PetscVector and PetscMatrix

### ISSUE THREAD

**Issue by fverdugo** [gridap/GridapPETSc.jl#51]
I think it would be convenient to store the `MPI.Comm` object inside the `PetscVector` and `PetscMatrix`.

It would be required e.g. to check if `comm==MPI.COMM_SELF` and select a suitable finalization strategy.

Once this is done, we can also remove  `MPI.Comm` from `PetscLinearSolver`.

**Comment by amartinhuertas** [comment]
Solved in https://github.com/gridap/GridapPETSc.jl/pull/42
