### ISSUE TITLE
Rename init! and finalize!

### ISSUE THREAD

**Issue by fverdugo** [gridap/GridapPETSc.jl#8]
@victorsndvg 

I think that  it can be a good idea to rename 
- `GridapPETSc.init!()` -> `GridapPETSc.Init()`
- `GridapPETSc.finalize!()` -> `GridapPETSc.Finalize()`

in order to be consistent with
- `MPI.Init()`
- `MPI.Finalize()`

Last time, I have suggested to use the versions with `!`. But now, by looking into the example in the README file, I see clearly that we want to be consistent with `MPI`. Sorry for the inconvenience...

Can you rename the functions? Thanks!

**Comment by victorsndvg** [comment]
done in a8f6b18

**Comment by fverdugo** [comment]
Closed via PR #9
